# Generated by Django 4.2.17 on 2025-05-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_postlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='community_postlike',
        ),
    ]
