# Generated by Django 5.2 on 2025-06-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0014_postdraft_postdraftimage"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postdraft",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.users"
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.users"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.users"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.users"
            ),
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
