# Generated by Django 5.2 on 2025-06-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("points", models.IntegerField(default=0)),
                ("certification", models.BooleanField(default=False)),
                ("login_type", models.CharField(default="normal", max_length=20)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IdVerification",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.users",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("id_number_front", models.CharField(max_length=6)),
                ("id_number_back", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "ID",
            },
        ),
    ]
